services:
  server:
    image: 322095785990.dkr.ecr.us-east-1.amazonaws.com/bia-beanstalk:${TAG}
    ports:
      - 80:8080
    environment:
      DB_SECRET_NAME: ${DB_SECRET_NAME}
      DB_REGION: ${DB_REGION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
