services:
  server:
    build: .
    ports:
      - 80:8080
    environment:
      DB_SECRET_NAME: rds!db-b4b74a63-2384-4065-9d98-71aa772b0ce2
      DB_REGION: us-east-1
      DB_HOST: bia.cfaxmljll1xz.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_NAME: bia
